"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sourcesByCategory = exports.sourcesByIndustry = exports.enabledSources = exports.sourceRegistry = void 0;
exports.sourceRegistry = [
    {
        id: "gov-cn-policy-library",
        name: "国务院政策文件库",
        tier: "T0",
        categories: ["policy", "china"],
        industries: ["generalPublic", "localLife", "financeInvestment", "educationResearch", "hrRecruiting"],
        method: "web",
        url: "https://www.gov.cn/zhengce/zuixin/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于国内重要政策、民生政策和行业政策的官方事实底座。"
    },
    {
        id: "mem-cn",
        name: "应急管理部",
        tier: "T0",
        categories: ["disaster", "publicSafety", "china", "local"],
        industries: ["generalPublic", "localLife", "operationsGrowth"],
        method: "web",
        url: "https://www.mem.gov.cn/xw/yjglbgzdt/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 60,
        requiresApiKey: false,
        enabled: true,
        notes: "用于防汛、防台风、地质灾害、救灾和安全生产等国内风险提醒。"
    },
    {
        id: "cac-cn",
        name: "中央网信办 / 国家网信办",
        tier: "T0",
        categories: ["policy", "china", "ai", "technology"],
        industries: ["aiProduct", "aiTechnology", "productManagement", "technologyEngineering", "contentCreator", "generalPublic"],
        method: "web",
        url: "https://www.cac.gov.cn/index.htm",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 360,
        requiresApiKey: false,
        enabled: true,
        notes: "用于人工智能、算法、数据、平台治理、个人信息和网络安全政策。"
    },
    {
        id: "xinhua-world",
        name: "新华网国际",
        tier: "T1",
        categories: ["world", "policy", "publicSafety"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth", "contentCreator"],
        method: "web",
        url: "https://www.news.cn/world/index.html",
        language: "zh",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 30,
        requiresApiKey: false,
        enabled: true,
        notes: "用于国际局势、战争冲突、外交、能源和重大公共事件的中文主流媒体报道。"
    },
    {
        id: "xinhua-tech",
        name: "新华网科技",
        tier: "T1",
        categories: ["technology", "ai", "product"],
        industries: ["aiProduct", "aiTechnology", "productManagement", "technologyEngineering", "educationResearch", "operationsGrowth"],
        method: "web",
        url: "https://www.news.cn/tech/index.html",
        language: "zh",
        regions: ["中国", "全球"],
        trustScore: 4,
        refreshMinutes: 120,
        requiresApiKey: false,
        enabled: true,
        notes: "用于 AI、机器人、芯片、自动驾驶、科研突破和科技产业动态。"
    },
    {
        id: "stats-cn-rss",
        name: "国家统计局 RSS",
        tier: "T0",
        categories: ["china", "policy", "finance"],
        industries: ["financeInvestment", "operationsGrowth", "consumerBrand", "generalPublic"],
        method: "rss",
        url: "https://www.stats.gov.cn/wzgl/rss/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 1440,
        requiresApiKey: false,
        enabled: true,
        notes: "用于宏观数据、消费、就业、行业运行等背景信息。"
    },
    {
        id: "stats-cn-data",
        name: "国家统计局数据发布",
        tier: "T0",
        categories: ["china", "finance", "consumer", "operations"],
        industries: ["operationsGrowth", "consumerBrand", "financeInvestment", "ecommerceRetail", "generalPublic"],
        method: "web",
        url: "https://www.stats.gov.cn/sj/zxfb/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于消费、价格、PMI、行业运行、企业利润等宏观数据候选。"
    },
    {
        id: "gdelt-doc-api",
        name: "GDELT DOC 2.0 API",
        tier: "T1",
        categories: ["world", "china", "policy", "publicSafety", "lightTrend"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth", "contentCreator"],
        method: "api",
        url: "https://api.gdeltproject.org/api/v2/doc/doc",
        language: "multi",
        regions: ["全球"],
        trustScore: 3,
        refreshMinutes: 30,
        requiresApiKey: false,
        enabled: true,
        notes: "用于全球新闻发现和多源线索聚合，不作为唯一事实确认来源。"
    },
    {
        id: "guardian-open-platform",
        name: "The Guardian Open Platform",
        tier: "T1",
        categories: ["world", "technology", "policy", "publicSafety"],
        industries: ["generalPublic", "aiTechnology", "technologyEngineering", "educationResearch", "contentCreator"],
        method: "api",
        url: "https://content.guardianapis.com/search",
        language: "en",
        regions: ["全球", "英国"],
        trustScore: 4,
        refreshMinutes: 60,
        requiresApiKey: true,
        enabled: false,
        licenseNote: "需要 API key，并在正式使用前确认展示和缓存限制。",
        notes: "用于国际新闻和科技政策的主流媒体补充。"
    },
    {
        id: "reliefweb-api",
        name: "ReliefWeb API",
        tier: "T0",
        categories: ["disaster", "publicSafety", "world"],
        industries: ["generalPublic", "localLife", "operationsGrowth"],
        method: "api",
        url: "https://api.reliefweb.int/v2/reports",
        language: "multi",
        regions: ["全球"],
        trustScore: 5,
        refreshMinutes: 60,
        requiresApiKey: false,
        enabled: true,
        notes: "用于全球灾害、人道危机和公共风险信息。"
    },
    {
        id: "gdacs-feed",
        name: "GDACS 灾害 Feed",
        tier: "T0",
        categories: ["disaster", "publicSafety"],
        industries: ["generalPublic", "localLife"],
        method: "rss",
        url: "https://www.gdacs.org/xml/rss.xml",
        language: "en",
        regions: ["全球"],
        trustScore: 5,
        refreshMinutes: 15,
        requiresApiKey: false,
        enabled: true,
        notes: "用于地震、热带气旋、洪水等全球灾害提醒。"
    },
    {
        id: "arxiv-cs-api",
        name: "arXiv Computer Science API",
        tier: "T0",
        categories: ["ai", "technology", "education"],
        industries: ["aiTechnology", "technologyEngineering", "educationResearch", "communicationsResearch", "aiProduct"],
        method: "api",
        url: "https://export.arxiv.org/api/query",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于 AI 和计算机科学研究趋势发现，需要再判断是否足够大众或行业重要。"
    },
    {
        id: "cas-science-news",
        name: "中国科学院科研动态",
        tier: "T0",
        categories: ["technology", "education", "healthcare"],
        industries: ["technologyEngineering", "educationResearch", "communicationsResearch", "healthcare"],
        method: "web",
        url: "https://www.cas.cn/syky/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于科研突破、研究机构动态和博士生需要的论文与科研线索。"
    },
    {
        id: "mohurd-construction",
        name: "住房和城乡建设部",
        tier: "T0",
        categories: ["policy", "china", "technology"],
        industries: ["architectureBuiltEnvironment", "technologyEngineering", "generalPublic"],
        method: "web",
        url: "https://www.mohurd.gov.cn/xinwen/gzdt/index.html",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于建筑、住房、城市更新和城乡建设相关政策动态。"
    },
    {
        id: "producthunt-api",
        name: "Product Hunt API",
        tier: "T2",
        categories: ["product", "technology", "startup"],
        industries: ["aiProduct", "productManagement", "startupBusiness", "contentCreator", "operationsGrowth"],
        method: "api",
        url: "https://api.producthunt.com/v2/api/graphql",
        language: "en",
        regions: ["全球"],
        trustScore: 3,
        refreshMinutes: 720,
        requiresApiKey: true,
        enabled: false,
        licenseNote: "需要开发者 token，适合作为产品趋势发现源。",
        notes: "用于新产品、新工具和轻量产品趋势发现。"
    },
    {
        id: "huggingface-blog",
        name: "Hugging Face Blog",
        tier: "T2",
        categories: ["ai", "technology"],
        industries: ["aiTechnology", "technologyEngineering", "aiProduct", "educationResearch"],
        method: "web",
        url: "https://huggingface.co/blog",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于开源模型、工具和 AI 社区动态。"
    },
    {
        id: "openai-news",
        name: "OpenAI News",
        tier: "T0",
        categories: ["ai", "product", "technology"],
        industries: ["aiProduct", "aiTechnology", "productManagement", "technologyEngineering", "educationResearch"],
        method: "web",
        url: "https://openai.com/news/",
        language: "en",
        regions: ["全球"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于 OpenAI 官方产品、研究和政策信息。"
    },
    {
        id: "deepmind-blog",
        name: "Google DeepMind Blog",
        tier: "T0",
        categories: ["ai", "technology"],
        industries: ["aiTechnology", "technologyEngineering", "educationResearch", "aiProduct"],
        method: "web",
        url: "https://deepmind.google/blog/",
        language: "en",
        regions: ["全球"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于 Google DeepMind 官方研究和产品相关动态。"
    },
    {
        id: "moe-cn",
        name: "教育部",
        tier: "T0",
        categories: ["education", "policy", "china"],
        industries: ["educationResearch", "teacher", "generalPublic"],
        method: "web",
        url: "https://www.moe.gov.cn/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于教师、教育行业、考试招生和教育政策相关信息。"
    },
    {
        id: "mohrss-cn",
        name: "人力资源和社会保障部",
        tier: "T0",
        categories: ["hr", "policy", "china"],
        industries: ["hrRecruiting", "generalPublic", "financeInvestment"],
        method: "web",
        url: "https://www.mohrss.gov.cn/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于就业、社保、人力资源、劳动政策等信息。"
    },
    {
        id: "chrm-mohrss",
        name: "中国人力资源市场网",
        tier: "T0",
        categories: ["hr", "policy", "china"],
        industries: ["hrRecruiting", "generalPublic", "teacher"],
        method: "web",
        url: "https://chrm.mohrss.gov.cn/announcement/",
        language: "zh",
        regions: ["中国"],
        trustScore: 4,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于招聘公告、人才目录、三支一扶、高校毕业生就业和地方紧缺人才信息。"
    },
    {
        id: "mofcom-cn",
        name: "商务部",
        tier: "T0",
        categories: ["ecommerce", "consumer", "policy", "china"],
        industries: ["ecommerceRetail", "consumerBrand", "operationsGrowth", "startupBusiness"],
        method: "web",
        url: "https://www.mofcom.gov.cn/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于消费、外贸、电商、商务政策相关信息。"
    },
    {
        id: "mofcom-consumption",
        name: "商务部市场运行和消费促进司",
        tier: "T0",
        categories: ["consumer", "ecommerce", "operations", "policy", "china"],
        industries: ["operationsGrowth", "consumerBrand", "ecommerceRetail", "startupBusiness", "generalPublic"],
        method: "web",
        url: "https://scyxs.mofcom.gov.cn/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于消费促进、市场运行、汽车流通、服务消费和电商相关政策动态。"
    },
    {
        id: "nhc-cn",
        name: "国家卫生健康委",
        tier: "T0",
        categories: ["healthcare", "policy", "publicSafety", "china"],
        industries: ["healthcare", "generalPublic", "localLife"],
        method: "web",
        url: "https://www.nhc.gov.cn/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于医疗健康、公共卫生和健康政策信息。"
    },
    {
        id: "mit-technology-review",
        name: "MIT Technology Review",
        tier: "T2",
        categories: ["technology", "ai", "healthcare"],
        industries: ["aiTechnology", "technologyEngineering", "healthcare", "educationResearch"],
        method: "web",
        url: "https://www.technologyreview.com/",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 720,
        enabled: false,
        requiresApiKey: false,
        licenseNote: "正式接入前需要确认内容抓取、引用和展示限制。",
        notes: "用于技术趋势和深度行业观察，适合低频精选。"
    }
];
exports.enabledSources = exports.sourceRegistry.filter((source) => source.enabled);
const sourcesByIndustry = (industry) => exports.sourceRegistry.filter((source) => source.industries.includes(industry));
exports.sourcesByIndustry = sourcesByIndustry;
const sourcesByCategory = (category) => exports.sourceRegistry.filter((source) => source.categories.includes(category));
exports.sourcesByCategory = sourcesByCategory;
