"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sourcesByCategory = exports.sourcesByIndustry = exports.enabledSources = exports.sourceRegistry = void 0;
exports.sourceRegistry = [
    {
        id: "gov-cn-policy-library",
        name: "国务院政策文件库",
        tier: "T0",
        categories: ["policy", "china"],
        industries: ["generalPublic", "localLife", "financeInvestment", "educationResearch", "hrRecruiting"],
        method: "web",
        url: "https://www.gov.cn/zhengce/zuixin/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于国内重要政策、民生政策和行业政策的官方事实底座。"
    },
    {
        id: "mem-cn",
        name: "应急管理部",
        tier: "T0",
        categories: ["disaster", "publicSafety", "china", "local"],
        industries: ["generalPublic", "localLife", "operationsGrowth"],
        method: "web",
        url: "https://www.mem.gov.cn/xw/yjglbgzdt/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 60,
        requiresApiKey: false,
        enabled: true,
        notes: "用于防汛、防台风、地质灾害、救灾和安全生产等国内风险提醒。"
    },
    {
        id: "cac-cn",
        name: "中央网信办 / 国家网信办",
        tier: "T0",
        categories: ["policy", "china", "ai", "technology"],
        industries: ["aiProduct", "aiTechnology", "productManagement", "technologyEngineering", "contentCreator", "generalPublic"],
        method: "web",
        url: "https://www.cac.gov.cn/index.htm",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 360,
        requiresApiKey: false,
        enabled: true,
        fallbackUrls: ["https://www.cac.gov.cn/"],
        notes: "用于人工智能、算法、数据、平台治理、个人信息和网络安全政策。"
    },
    {
        id: "xinhua-world",
        name: "新华网国际",
        tier: "T1",
        categories: ["world", "policy", "publicSafety"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth", "contentCreator"],
        method: "web",
        url: "https://www.news.cn/world/index.html",
        language: "zh",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 30,
        requiresApiKey: false,
        enabled: true,
        role: "both",
        coverageLanes: ["global", "chinaImpact"],
        notes: "用于国际局势、战争冲突、外交、能源和重大公共事件的中文主流媒体报道。"
    },
    {
        id: "bbc-world-rss",
        name: "BBC World RSS",
        tier: "T1",
        categories: ["world", "policy", "publicSafety"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth", "contentCreator"],
        method: "rss",
        url: "https://feeds.bbci.co.uk/news/world/rss.xml",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 30,
        requiresApiKey: false,
        enabled: false,
        role: "both",
        coverageLanes: ["global", "chinaImpact"],
        notes: "运行环境连接不稳定，暂不作为默认来源；恢复前不能计入覆盖完成度。"
    },
    {
        id: "gov-uk-news",
        name: "GOV.UK News and Communications",
        tier: "T0",
        categories: ["world", "policy", "local", "publicSafety", "finance"],
        industries: ["generalPublic", "localLife", "financeInvestment", "hrRecruiting", "operationsGrowth", "teacher"],
        method: "rss",
        url: "https://www.gov.uk/search/news-and-communications.atom?order=updated-newest",
        language: "en",
        regions: ["英国"],
        trustScore: 5,
        refreshMinutes: 30,
        requiresApiKey: false,
        enabled: true,
        role: "both",
        coverageLanes: ["local", "industry", "global"],
        notes: "英国政府官方更新流，用于英国政策、公共服务、监管和风险信息。"
    },
    {
        id: "bbc-business-rss",
        name: "BBC Business RSS",
        tier: "T1",
        categories: ["world", "policy", "finance", "operations"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth", "ecommerceRetail"],
        method: "rss",
        url: "https://feeds.bbci.co.uk/news/business/rss.xml",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 30,
        requiresApiKey: false,
        enabled: false,
        role: "both",
        coverageLanes: ["global", "chinaImpact", "industry"],
        notes: "运行环境连接不稳定，暂不作为默认来源；恢复前不能计入覆盖完成度。"
    },
    {
        id: "bbc-technology-rss",
        name: "BBC Technology RSS",
        tier: "T1",
        categories: ["technology", "ai", "product"],
        industries: ["aiProduct", "aiTechnology", "productManagement", "technologyEngineering"],
        method: "rss",
        url: "https://feeds.bbci.co.uk/news/technology/rss.xml",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 60,
        requiresApiKey: false,
        enabled: false,
        role: "discovery",
        coverageLanes: ["industry"],
        notes: "运行环境连接不稳定，暂不作为默认来源；恢复前不能计入覆盖完成度。"
    },
    {
        id: "npr-world-rss",
        name: "NPR World RSS",
        tier: "T1",
        categories: ["world", "policy", "publicSafety"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth", "contentCreator"],
        method: "rss",
        url: "https://feeds.npr.org/1004/rss.xml",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 30,
        requiresApiKey: false,
        enabled: true,
        role: "both",
        coverageLanes: ["global", "chinaImpact"],
        notes: "用于补充国际冲突、外交、政权变化与跨国公共事件。"
    },
    {
        id: "sky-world-rss",
        name: "Sky News World RSS",
        tier: "T1",
        categories: ["world", "policy", "publicSafety"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth", "contentCreator"],
        method: "rss",
        url: "https://feeds.skynews.com/feeds/rss/world.xml",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 30,
        requiresApiKey: false,
        enabled: true,
        role: "discovery",
        coverageLanes: ["global"],
        notes: "用于扩大国际突发线索池，重大事实仍需官方或第二个主流来源确认。"
    },
    {
        id: "wsj-world-rss",
        name: "WSJ World News RSS",
        tier: "T1",
        categories: ["world", "policy", "finance", "operations"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth", "ecommerceRetail"],
        method: "rss",
        url: "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 60,
        requiresApiKey: false,
        enabled: false,
        role: "discovery",
        coverageLanes: ["global", "chinaImpact"],
        notes: "当前公开 Feed 内容长期未更新，暂不计入时效覆盖。"
    },
    {
        id: "france24-middle-east-rss",
        name: "France 24 Middle East RSS",
        tier: "T1",
        categories: ["world", "policy", "publicSafety"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth", "contentCreator"],
        method: "rss",
        url: "https://www.france24.com/en/middle-east/rss",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 30,
        requiresApiKey: false,
        enabled: true,
        role: "discovery",
        coverageLanes: ["global", "chinaImpact"],
        notes: "用于补充中东冲突、停火、能源与航运的即时线索；重大事件仍需交叉核验。"
    },
    {
        id: "france24-asia-pacific-rss",
        name: "France 24 Asia-Pacific RSS",
        tier: "T1",
        categories: ["world", "policy", "publicSafety"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth", "contentCreator"],
        method: "rss",
        url: "https://www.france24.com/en/asia-pacific/rss",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 60,
        requiresApiKey: false,
        enabled: true,
        role: "discovery",
        coverageLanes: ["global", "chinaImpact"],
        notes: "用于补充亚太政策、地区局势与接近中国用户的公共事件线索。"
    },
    {
        id: "cnbc-world-rss",
        name: "CNBC World News RSS",
        tier: "T1",
        categories: ["world", "policy", "finance", "operations"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth", "ecommerceRetail"],
        method: "rss",
        url: "https://www.cnbc.com/id/100727362/device/rss/rss.html",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 30,
        requiresApiKey: false,
        enabled: true,
        role: "discovery",
        coverageLanes: ["global", "chinaImpact"],
        notes: "用于补充关税、贸易、能源、航运、政策和全球市场变化线索。"
    },
    {
        id: "un-news-rss",
        name: "联合国新闻 RSS",
        tier: "T0",
        categories: ["world", "policy", "disaster", "publicSafety"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth", "localLife"],
        method: "rss",
        url: "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
        language: "en",
        regions: ["全球"],
        trustScore: 5,
        refreshMinutes: 60,
        requiresApiKey: false,
        enabled: true,
        role: "confirmation",
        coverageLanes: ["global", "disaster"],
        notes: "用于确认战争、人道危机、国际组织决议和跨国公共风险。"
    },
    {
        id: "mfa-cn-news",
        name: "中国外交部",
        tier: "T0",
        categories: ["world", "china", "policy"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth"],
        method: "web",
        url: "https://www.mfa.gov.cn/wjdt_674879/fyrbt_674889/",
        language: "zh",
        regions: ["中国", "全球"],
        trustScore: 5,
        refreshMinutes: 60,
        requiresApiKey: false,
        enabled: true,
        role: "confirmation",
        coverageLanes: ["global", "chinaImpact"],
        standaloneCandidate: false,
        notes: "用于确认重大国际事件中的中国立场、领事提醒和外交政策变化。"
    },
    {
        id: "mofcom-trade",
        name: "商务部新闻发布",
        tier: "T0",
        categories: ["world", "china", "policy", "finance", "ecommerce"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth", "ecommerceRetail", "consumerBrand"],
        method: "web",
        url: "https://www.mofcom.gov.cn/xwfb/",
        language: "zh",
        regions: ["中国", "全球"],
        trustScore: 5,
        refreshMinutes: 120,
        requiresApiKey: false,
        enabled: true,
        role: "confirmation",
        coverageLanes: ["chinaImpact", "industry"],
        notes: "用于确认关税、外贸、出口管制、跨境电商和对外经贸政策。"
    },
    {
        id: "xinhua-tech",
        name: "新华网科技",
        tier: "T1",
        categories: ["technology", "ai", "product"],
        industries: ["aiProduct", "aiTechnology", "productManagement", "technologyEngineering", "educationResearch", "operationsGrowth"],
        method: "web",
        url: "https://www.news.cn/tech/index.html",
        language: "zh",
        regions: ["中国", "全球"],
        trustScore: 4,
        refreshMinutes: 120,
        requiresApiKey: false,
        enabled: true,
        notes: "用于 AI、机器人、芯片、自动驾驶、科研突破和科技产业动态。"
    },
    {
        id: "stats-cn-rss",
        name: "国家统计局 RSS",
        tier: "T0",
        categories: ["china", "policy", "finance"],
        industries: ["financeInvestment", "operationsGrowth", "consumerBrand", "generalPublic"],
        method: "rss",
        url: "https://www.stats.gov.cn/wzgl/rss/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 1440,
        requiresApiKey: false,
        enabled: true,
        notes: "用于宏观数据、消费、就业、行业运行等背景信息。"
    },
    {
        id: "stats-cn-data",
        name: "国家统计局数据发布",
        tier: "T0",
        categories: ["china", "finance", "consumer", "operations"],
        industries: ["operationsGrowth", "consumerBrand", "financeInvestment", "ecommerceRetail", "generalPublic"],
        method: "web",
        url: "https://www.stats.gov.cn/sj/zxfb/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于消费、价格、PMI、行业运行、企业利润等宏观数据候选。"
    },
    {
        id: "gdelt-doc-api",
        name: "GDELT DOC 2.0 API",
        tier: "T1",
        categories: ["world", "china", "policy", "publicSafety", "lightTrend"],
        industries: ["generalPublic", "financeInvestment", "operationsGrowth", "contentCreator"],
        method: "api",
        url: "https://api.gdeltproject.org/api/v2/doc/doc",
        language: "multi",
        regions: ["全球"],
        trustScore: 3,
        refreshMinutes: 30,
        requiresApiKey: false,
        enabled: false,
        role: "discovery",
        coverageLanes: ["global", "chinaImpact"],
        notes: "用于全球新闻发现和多源线索聚合，不作为唯一事实确认来源；当前运行环境连接不稳定，恢复前不计入默认抓取。"
    },
    {
        id: "guardian-open-platform",
        name: "The Guardian Open Platform",
        tier: "T1",
        categories: ["world", "technology", "policy", "publicSafety"],
        industries: ["generalPublic", "aiTechnology", "technologyEngineering", "educationResearch", "contentCreator"],
        method: "api",
        url: "https://content.guardianapis.com/search",
        language: "en",
        regions: ["全球", "英国"],
        trustScore: 4,
        refreshMinutes: 60,
        requiresApiKey: true,
        enabled: false,
        licenseNote: "需要 API key，并在正式使用前确认展示和缓存限制。",
        notes: "用于国际新闻和科技政策的主流媒体补充。"
    },
    {
        id: "reliefweb-api",
        name: "ReliefWeb API",
        tier: "T0",
        categories: ["disaster", "publicSafety", "world"],
        industries: ["generalPublic", "localLife", "operationsGrowth"],
        method: "api",
        url: "https://api.reliefweb.int/v2/reports",
        language: "multi",
        regions: ["全球"],
        trustScore: 5,
        refreshMinutes: 60,
        requiresApiKey: false,
        enabled: true,
        notes: "用于全球灾害、人道危机和公共风险信息。"
    },
    {
        id: "gdacs-feed",
        name: "GDACS 灾害 Feed",
        tier: "T0",
        categories: ["disaster", "publicSafety"],
        industries: ["generalPublic", "localLife"],
        method: "rss",
        url: "https://www.gdacs.org/xml/rss.xml",
        language: "en",
        regions: ["全球"],
        trustScore: 5,
        refreshMinutes: 15,
        requiresApiKey: false,
        enabled: true,
        role: "confirmation",
        coverageLanes: ["disaster"],
        notes: "用于地震、热带气旋、洪水等全球灾害提醒。"
    },
    {
        id: "arxiv-cs-api",
        name: "arXiv Computer Science API",
        tier: "T0",
        categories: ["ai", "technology", "education"],
        industries: ["aiTechnology", "technologyEngineering", "educationResearch", "communicationsResearch", "aiProduct"],
        method: "api",
        url: "https://export.arxiv.org/api/query",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于 AI 和计算机科学研究趋势发现，需要再判断是否足够大众或行业重要。"
    },
    {
        id: "cas-science-news",
        name: "中国科学院科研动态",
        tier: "T0",
        categories: ["technology", "education", "healthcare"],
        industries: ["technologyEngineering", "educationResearch", "communicationsResearch", "healthcare"],
        method: "web",
        url: "https://www.cas.cn/syky/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于科研突破、研究机构动态和博士生需要的论文与科研线索。"
    },
    {
        id: "mohurd-construction",
        name: "住房和城乡建设部",
        tier: "T0",
        categories: ["policy", "china", "technology"],
        industries: ["architectureBuiltEnvironment", "technologyEngineering", "generalPublic"],
        method: "web",
        url: "https://www.mohurd.gov.cn/xinwen/gzdt/index.html",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        fallbackUrls: ["https://www.mohurd.gov.cn/"],
        notes: "用于建筑、住房、城市更新和城乡建设相关政策动态。"
    },
    {
        id: "producthunt-api",
        name: "Product Hunt API",
        tier: "T2",
        categories: ["product", "technology", "startup"],
        industries: ["aiProduct", "productManagement", "startupBusiness", "contentCreator", "operationsGrowth"],
        method: "api",
        url: "https://api.producthunt.com/v2/api/graphql",
        language: "en",
        regions: ["全球"],
        trustScore: 3,
        refreshMinutes: 720,
        requiresApiKey: true,
        enabled: false,
        licenseNote: "需要开发者 token，适合作为产品趋势发现源。",
        notes: "用于新产品、新工具和轻量产品趋势发现。"
    },
    {
        id: "huggingface-blog",
        name: "Hugging Face Blog",
        tier: "T2",
        categories: ["ai", "technology"],
        industries: ["aiTechnology", "technologyEngineering", "aiProduct", "educationResearch"],
        method: "web",
        url: "https://huggingface.co/blog",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: false,
        role: "discovery",
        coverageLanes: ["industry"],
        notes: "用于开源模型、工具和 AI 社区动态；当前运行环境的 Node 网络连接不稳定，恢复前不计入默认抓取。"
    },
    {
        id: "techcrunch-ai-rss",
        name: "TechCrunch AI RSS",
        tier: "T1",
        categories: ["ai", "technology", "product", "startup"],
        industries: ["aiProduct", "aiTechnology", "productManagement", "technologyEngineering", "startupBusiness"],
        method: "rss",
        url: "https://techcrunch.com/category/artificial-intelligence/feed/",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 120,
        requiresApiKey: false,
        enabled: true,
        role: "discovery",
        coverageLanes: ["industry"],
        notes: "用于 AI 产品、创业公司、融资和行业动作的发现；具体事实仍需回看原文或官方发布。"
    },
    {
        id: "openai-news",
        name: "OpenAI News",
        tier: "T0",
        categories: ["ai", "product", "technology"],
        industries: ["aiProduct", "aiTechnology", "productManagement", "technologyEngineering", "educationResearch"],
        method: "rss",
        url: "https://openai.com/news/rss.xml",
        language: "en",
        regions: ["全球"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        role: "confirmation",
        coverageLanes: ["industry"],
        notes: "用于 OpenAI 官方产品、研究和政策信息。"
    },
    {
        id: "theverge-ai-rss",
        name: "The Verge AI RSS",
        tier: "T1",
        categories: ["ai", "technology", "product"],
        industries: ["aiProduct", "aiTechnology", "productManagement", "technologyEngineering"],
        method: "rss",
        url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 60,
        requiresApiKey: false,
        enabled: true,
        role: "discovery",
        coverageLanes: ["industry"],
        notes: "用于补充 AI 产品、平台策略、模型发布与消费者应用的行业线索。"
    },
    {
        id: "deepmind-blog",
        name: "Google DeepMind Blog",
        tier: "T0",
        categories: ["ai", "technology"],
        industries: ["aiTechnology", "technologyEngineering", "educationResearch", "aiProduct"],
        method: "rss",
        url: "https://deepmind.google/blog/rss.xml",
        language: "en",
        regions: ["全球"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        role: "confirmation",
        coverageLanes: ["industry"],
        notes: "用于 Google DeepMind 官方研究和产品相关动态。"
    },
    {
        id: "moe-cn",
        name: "教育部",
        tier: "T0",
        categories: ["education", "policy", "china"],
        industries: ["educationResearch", "teacher", "generalPublic"],
        method: "web",
        url: "https://www.moe.gov.cn/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于教师、教育行业、考试招生和教育政策相关信息。"
    },
    {
        id: "eol-education",
        name: "中国教育在线要闻",
        tier: "T1",
        categories: ["education", "policy", "china"],
        industries: ["educationResearch", "teacher"],
        method: "web",
        url: "https://www.eol.cn/news/yaowen/",
        language: "zh",
        regions: ["中国"],
        trustScore: 4,
        refreshMinutes: 360,
        requiresApiKey: false,
        enabled: true,
        role: "discovery",
        coverageLanes: ["industry"],
        notes: "用于补充教育政策、基础教育、高等教育、职业教育和学校治理的每日行业线索；重要事实需回到教育部门或原始发布方确认。"
    },
    {
        id: "jyb-education",
        name: "中国教育新闻网",
        tier: "T1",
        categories: ["education", "policy", "china"],
        industries: ["educationResearch", "teacher"],
        method: "web",
        url: "http://www.jyb.cn/",
        language: "zh",
        regions: ["中国"],
        trustScore: 4,
        refreshMinutes: 360,
        requiresApiKey: false,
        enabled: true,
        role: "discovery",
        coverageLanes: ["industry"],
        notes: "中国教育报刊社主办，用于补充教学、教师发展、学校治理和各学段教育实践的每日行业线索。"
    },
    {
        id: "mohrss-cn",
        name: "人力资源和社会保障部",
        tier: "T0",
        categories: ["hr", "policy", "china"],
        industries: ["hrRecruiting", "generalPublic", "financeInvestment"],
        method: "web",
        url: "https://www.mohrss.gov.cn/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于就业、社保、人力资源、劳动政策等信息。"
    },
    {
        id: "chrm-mohrss",
        name: "中国人力资源市场网",
        tier: "T0",
        categories: ["hr", "policy", "china"],
        industries: ["hrRecruiting", "generalPublic", "teacher"],
        method: "web",
        url: "https://chrm.mohrss.gov.cn/announcement/",
        language: "zh",
        regions: ["中国"],
        trustScore: 4,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于招聘公告、人才目录、三支一扶、高校毕业生就业和地方紧缺人才信息。"
    },
    {
        id: "mofcom-cn",
        name: "商务部",
        tier: "T0",
        categories: ["ecommerce", "consumer", "policy", "china"],
        industries: ["ecommerceRetail", "consumerBrand", "operationsGrowth", "startupBusiness"],
        method: "web",
        url: "https://www.mofcom.gov.cn/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于消费、外贸、电商、商务政策相关信息。"
    },
    {
        id: "mofcom-consumption",
        name: "商务部市场运行和消费促进司",
        tier: "T0",
        categories: ["consumer", "ecommerce", "operations", "policy", "china"],
        industries: ["operationsGrowth", "consumerBrand", "ecommerceRetail", "startupBusiness", "generalPublic"],
        method: "web",
        url: "https://scyxs.mofcom.gov.cn/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        fallbackUrls: ["https://www.mofcom.gov.cn/"],
        notes: "用于消费促进、市场运行、汽车流通、服务消费和电商相关政策动态。"
    },
    {
        id: "nhc-cn",
        name: "国家卫生健康委",
        tier: "T0",
        categories: ["healthcare", "policy", "publicSafety", "china"],
        industries: ["healthcare", "generalPublic", "localLife"],
        method: "web",
        url: "https://www.nhc.gov.cn/",
        language: "zh",
        regions: ["中国"],
        trustScore: 5,
        refreshMinutes: 720,
        requiresApiKey: false,
        enabled: true,
        notes: "用于医疗健康、公共卫生和健康政策信息。"
    },
    {
        id: "mit-technology-review",
        name: "MIT Technology Review",
        tier: "T2",
        categories: ["technology", "ai", "healthcare"],
        industries: ["aiTechnology", "technologyEngineering", "healthcare", "educationResearch"],
        method: "web",
        url: "https://www.technologyreview.com/",
        language: "en",
        regions: ["全球"],
        trustScore: 4,
        refreshMinutes: 720,
        enabled: false,
        requiresApiKey: false,
        licenseNote: "正式接入前需要确认内容抓取、引用和展示限制。",
        notes: "用于技术趋势和深度行业观察，适合低频精选。"
    }
];
exports.enabledSources = exports.sourceRegistry.filter((source) => source.enabled);
const sourcesByIndustry = (industry) => exports.sourceRegistry.filter((source) => source.industries.includes(industry));
exports.sourcesByIndustry = sourcesByIndustry;
const sourcesByCategory = (category) => exports.sourceRegistry.filter((source) => source.categories.includes(category));
exports.sourcesByCategory = sourcesByCategory;
